---
title: "Probability Theory"
---


## Assignment I

\begin{align*}
P(T \cap S) &= P(T|S) \cdot P(S) \\
            &= 0.2 \cdot 0.3 \\
            &= 0.06
\end{align*}


\begin{align*}
P(T \cap \overline{S}) &= P(T|\overline{S}) \cdot P(\overline{S}) \\
                       &= 0.6 \cdot 0.7 \\
                       &= 0.42
\end{align*}




\begin{align*}
P(\overline{T} \cap S) &= P(\overline{T}|{S}) \cdot P({S}) \\
                       &= 0.8 \cdot 0.3 \\
                       &= 0.24
\end{align*}



\begin{align*}
P(\overline{T} \cap \overline{S}) &= P(\overline{T}|\overline{S}) \cdot P(\overline{S}) \\
                       &= 0.4 \cdot 0.7 \\
                       &= 0.28
\end{align*}






## Assignment II

**1.  What is the percentage of customers using all three devices? ** \
--> 0.5 %

**2.  What is the percentage of customers using at least two devices? **\
--> To calculate this, sum the percentages of customers using both Computer and Tablet, Tablet and Smartphone, Smartphone and Computer, and the percentage of customers using all three devices.\
3.3 + 7.3 + 8.8 + 0.5 = 19.9 %

**3.  What is the percentage of customers using only one device?**\
--> It is the sum of the rest of the percentages.\
10 + 27.8 + 42.3 = 80.1 %








## Assignment III
Using Bayes Theorem:


\begin{align*}
P(A|B) &= \frac{P(B|A) \cdot P(A)}{P(B|A) \cdot P(A) + P(B|\overline{A}) \cdot P(\overline{A)}} \\
&= \frac{0.97 \cdot 0.04}{0.97 \cdot 0.04 + 0.01 \cdot (1 - 0.04)} \\
&\approx 0.80165 
\end{align*}

\
\



\begin{align*}
P(\overline{A}|B) &= \frac{P(B|\overline{A}) \cdot P(\overline{A)}}{P(B|\overline{A}) \cdot P(\overline{A}) + P(B|A) \cdot P(A)} \\
&= \frac{0.01 \cdot (1 - 0.04)}{0.01 \cdot (1 - 0.04) + 0.97 \cdot 0.04} \\
&\approx 0.19835
\end{align*}



These results show that in case the alarm is triggered, there is a possibility of about **80.165%** that the product is flawless and a probability of **19.835%** that the product is faulty.


